spring.application.name=monitoring-meteo

server.port=8080

# SQLite Configuration - Chemin ABSOLU
spring.datasource.url=jdbc:sqlite:C:/Users/user/monitoring-meteo/database/monitoring_meteo.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Static files (vos fichiers HTML existants)
spring.web.resources.static-locations=file:C:/Users/user/monitoring-meteo/public/